.Dd November 9, 2025
.Dt OCHRE 1
.Os Darwin
.Sh NAME
.Nm ochre
.Nd macOS optical character recognition via the command line
.Sh SYNOPSIS
.Nm
.Op Fl jhv
.Sh DESCRIPTION
.Nm
is a command line interface for the built-in optical character recognition
capabilities in macOS.
.Pp
The following flags are supported:
.Bl -tag -width -indent
.It Fl j -json
Output JSON
.It Fl h -help
Print help and exit.
.It Fl v -version
Print program name and version, and exit.
.El
.Pp
Returns 0 on success and greater than 0 on error or failure.
.Sh AUTHORS
.An Sveinbjorn Thordarson <sveinbjorn@sveinbjorn.org>
.An Based on ocrImage by David Phillip Oster .
